language: node_js
node_js:
  - "16.14"
os:
  - linux
dist:
  - focal
directories:
  - node_modules
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export PUBLIC_URL=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo ""; else echo "/pr/$TRAVIS_PULL_REQUEST"; fi)
  - echo $PUBLIC_URL
  - npm install
  - npm run build
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, BRANCH=$BRANCH"
  - cd wms-assistent
  - npm install
  - npm run build
  - cd ..

after_success:
  - ./deploy.sh $BRANCH
  - ./deploy_wms-assistent.sh $BRANCH
  - ./deploy_django.sh $BRANCH

notifications:
  slack:
    on_success: change
    on_failure: change
before_install:
  - sudo apt-get install -y sshpass
