# Generated by Django 3.0.4 on 2020-05-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okologiskegrunnkart', '0004_underkartlag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('wmslayer', models.CharField(blank=True, max_length=100)),
                ('legendeurl', models.CharField(blank=True, max_length=500)),
                ('publiser', models.BooleanField(default=False)),
                ('turnedon', models.BooleanField(default=False)),
                ('hovedkartlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublag', to='okologiskegrunnkart.Kartlag')),
            ],
        ),
        migrations.DeleteModel(
            name='UnderKartlag',
        ),
    ]
