# Generated by Django 3.0.7 on 2020-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okologiskegrunnkart', '0008_sublag_suggested'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WmsHelper',
        ),
        migrations.RemoveField(
            model_name='kartlag',
            name='wmsinfolayers',
        ),
        migrations.AddField(
            model_name='sublag',
            name='klikktekst',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sublag',
            name='klikktekst2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sublag',
            name='klikkurl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sublag',
            name='testkoordinater',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
