# Generated by Django 3.0.7 on 2020-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okologiskegrunnkart', '0010_kartlag_aggregatedwmslayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublag',
            name='faktaark',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
