# Generated by Django 3.0.7 on 2020-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okologiskegrunnkart', '0012_auto_20201029_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublag',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
