# Generated by Django 3.0.4 on 2020-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataeier',
            name='logourl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dataeier',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kartlag',
            name='faktaark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kartlag',
            name='karturl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kartlag',
            name='klikkurl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kartlag',
            name='kode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
