# Generated by Django 3.0.4 on 2020-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0002_remove_kartlag_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartlag',
            name='geonorgeurl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='kartlag',
            name='legendeurl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='kartlag',
            name='produktark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='kartlag',
            name='publiser',
            field=models.BooleanField(default=False),
        ),
    ]
