# Generated by Django 3.0.4 on 2020-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0002_auto_20200312_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartlag',
            name='tag',
            field=models.ManyToManyField(null=True, to='forvaltningsportal.Tag'),
        ),
    ]
