# Generated by Django 3.0.4 on 2020-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0003_auto_20200312_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartlag',
            name='tag',
            field=models.ManyToManyField(blank=True, to='forvaltningsportal.Tag'),
        ),
    ]
