# Generated by Django 3.0.4 on 2020-05-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0005_auto_20200506_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sublag',
            old_name='turnedon',
            new_name='erSynlig',
        ),
    ]
