# Generated by Django 3.0.7 on 2020-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0007_auto_20200609_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublag',
            name='suggested',
            field=models.BooleanField(default=False),
        ),
    ]
