# Generated by Django 3.0.4 on 2020-05-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0007_data_migrering_wmslag_til_sublag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kartlag',
            name='legendeurl',
        ),
        migrations.RemoveField(
            model_name='kartlag',
            name='wmslayer',
        ),
    ]
