# Generated by Django 3.0.7 on 2020-08-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0009_auto_20200805_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartlag',
            name='aggregatedwmslayer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
