# Generated by Django 3.0.7 on 2020-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forvaltningsportal', '0013_sublag_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sublag',
            old_name='publiser',
            new_name='publisertest',
        ),
        migrations.RemoveField(
            model_name='kartlag',
            name='publiser',
        ),
        migrations.AddField(
            model_name='sublag',
            name='publiserprod',
            field=models.BooleanField(default=False),
        ),
    ]
